### ISSUE TITLE
Dev-Question: API details

### ISSUE THREAD

**Issue by seichner** [leoschweizer/moneymoney-coinbase-pro#1]
Hello!

I just used your Gdax-Extension and wondered: how did you manage to get the input fields for API key/secret/passphrase? (see screenshot)
Looking through your code and MoneyMoney docs i didn't see anything that jumped to my eye... i have two custom extensions here where i need to abuse the default username/password field for that. Any hint? :)

Thank you!
 Sebastian

![screenshot_05_01_18__18_46](https://user-images.githubusercontent.com/120468/34621366-244919b8-f249-11e7-8e85-708ad6798720.png)

**Comment by leoschweizer** [comment]
@seichner unfortunately, this part can't be influenced through the API at all (yet?). You have to contact the MoneyMoney support and they will provide a custom build which displays the required input fields based on your `bankCode`. However, this might only be an option if you intend to publish your extensions.
