### ISSUE TITLE
Error "Bad Request"

### ISSUE THREAD

**Issue by dark-m0de** [leoschweizer/moneymoney-coinbase-pro#12]
Dear Leo,
I'm unable to update my account at Coinbase Pro for quite a while now. Feel free to check the attached [error.log](https://github.com/leoschweizer/moneymoney-coinbase-pro/files/8053172/error.log).
I even set up the account again an generated a new API key. However, the issue still exists.
Do you have any guidance for me how to get rid of the issue?
BR, Conrad

**Comment by Duffycola** [comment]
I get the same error. It appears XRP is a delisted coin and not supported anymore?
When you manually go to the address https://api.pro.coinbase.com/products/XRP-EUR/ticker it returns {"message":"Not allowed for delisted products"}.

I've noticed before that the extension has a few problems with the many new coins. When I bought some alts before I wanted to try to buy a small number of all alts and noticed that some were always missing, giving me a false total.

**Comment by Duffycola** [comment]
Apparently XRP was briefly visible in coinbase pro but then delisted..
I was able to work around the issue by editing the extension like so:

>                local balanceCurrency = value["currency"]
>                if balanceCurrency == "XRP" then
>                        goto continue
>                end
>                ...
>                if balanceCurrency == nativeCurrency then
>                ...
>                else
>                ...
>                end
>                ::continue::

You have to use MoneyMoney beta to be able to disable extension signature validation as well in the settings.

**Comment by trulyari** [comment]
> Apparently XRP was briefly visible in coinbase pro but then delisted.. I was able to work around the issue by editing the extension like so:
> 
> > ```
> >            local balanceCurrency = value["currency"]
> >            if balanceCurrency == "XRP" then
> >                    goto continue
> >            end
> >            ...
> >            if balanceCurrency == nativeCurrency then
> >            ...
> >            else
> >            ...
> >            end
> >            ::continue::
> > ```
> 
> You have to use MoneyMoney beta to be able to disable extension signature validation as well in the settings.

Hi @Duffycola . I have the same issue with XRP. 

I deactivated the signature verification and I'm on the Beta version of the app.
However, when I edit the `Coinbase Pro.lua` file, the Coinbase pro account option totally disappears from MoneyMoney and I can no longer see it or add my Coinbase pro account anymore.

Can you please paste the edited code here completely, with all the correct indentations? Thanks!

**Comment by Duffycola** [comment]
I've made a pull request here #13

**Comment by Duffycola** [comment]
If you're only interested in BTC and ETH, for example, you can speed this up further using this line:

> if not (balanceCurrency == "BTC") and not(balanceCurrency == "ETH") then goto continue end

**Comment by Duffycola** [comment]
If you like this patch feel free to send a coffee to this wallet lol

BTC 37LfJper7QuThx5qEA1raacBaX6jS7eZBn
ETH 0xCf0d0C239b9d7f1BD76fe9cd013E679f5F9f4e88

**Comment by TeeJayR** [comment]
Alternative proposal to fix the bad request without hardcoding any currency: https://github.com/leoschweizer/moneymoney-coinbase-pro/pull/14

**Comment by leoschweizer** [comment]
#14 is now merged + signed + released, so this should be fixed
