### ISSUE TITLE
Coinbase Pro Support

### ISSUE THREAD

**Issue by qoomon** [leoschweizer/moneymoney-coinbase-pro#2]
Hi,

first of all thank you so much for this useful extension.

**Coinbase** announced to relaunch **gdax** under [Coinbase Pro](pro.coinbase.com), may you could create an other extension for **Coinbase Pro** as-well? That would be great!

Regards

**Comment by leoschweizer** [comment]
@qoomon currently, the API docs for Coinbase Pro link directly to those of GDAX, so this extension might actually work as is for Coinbase Pro as well.

**Comment by qoomon** [comment]
ok great, lets hope the will not shout down gdax api in the near future 😄
