### ISSUE TITLE
GDAX Deprecation Notice

### ISSUE THREAD

**Issue by TheSerapher** [leoschweizer/moneymoney-coinbase-pro#3]
Hey @leoschweizer ,

Thanks for your great plugin! Was super happy to see it also supports Coinbase Pro.

Eventually all *.gdax.com domains will be deactivated so either renaming the plugin or offering a different plugin to point the coinbase Pro API would be great.

Since I was unable to find documentation about the MoneyMoney signature I could't just update the plugin myself and open a PR :(

Edit: here the notice: https://docs.gdax.com/#introduction

**Comment by leoschweizer** [comment]
@TheSerapher I will update the endpoints (and probably rename the repository and plugin) before the gdax urls are deactivated, but there is plenty of time left before that happens ;)

**Comment by TheSerapher** [comment]
That's good to know! Thanks for your quick reply :-)

**Comment by qoomon** [comment]
Since today I get 'Bad Request' error if I refresh accounts.

**Comment by leoschweizer** [comment]
@qoomon there have been a lot of temporary outages of the API lately and this is likely one of them. The GDAX API should be operational until the end of the year according to https://docs.gdax.com/

**Comment by qoomon** [comment]
okay i will wait some days and try it again, thx

**Comment by TheSerapher** [comment]
@qoomon This is caused by a new currency being added (ETC) but not implemented in their API yet. You can see it in their WebUI but the API calls for it fails with 400 Bad Request. 

Once implemented in the API it should work again.

**Comment by qoomon** [comment]
thx

**Comment by leoschweizer** [comment]
The extension for Coinbase Pro is now available at https://moneymoney-app.com/extensions/

You will have to remove your GDAX account from MoneyMoney and add a new account for Coinbase Pro.
